### ISSUE TITLE
use `isAssignmentAllowed(..)` for arguments and return values

### ISSUE THREAD

**Issue by getify** [getify/Typl#31]
This example currently shows errors for both the argument type mismatch and the return type mismatch. Should use the same check/rules (number subtypes, etc) as normal assignment, and show no errors.

```js
function foo(x = number) {
	if (x > 4) {
		return x;
	}
	return int`0`;
}

var y = foo(int`3`);
```

**Comment by getify** [comment]
BTW, the reason for `isAssignmentAllowed(..)` being a good name in both these places is that conceptually, arguments are "assigned" to parameters, and return expressions are "assigned" to function returns.

**Comment by aydakarami250-prog** [comment]
Fuck you
