### ISSUE TITLE
Help in Typl ESLint Plugin

### ISSUE THREAD

**Issue by Attrash-Islam** [getify/Typl#42]
Hi @getify 
I'm working on eslint plugin for your nice type checker 🌟 .

![image](https://user-images.githubusercontent.com/7091543/56220685-862a4980-6071-11e9-98a7-d56654037c40.png)

I intended to write the code to be ES5-Compatible so I don't need to transpile it.

I'm confused how can I push the errors into the eslint API 😕.

I think that doing it as so in ESLint will give the Developer good experience to integrate with Editors and CI tasks. So I went with 0 rules and I'm trying to use a processor to type check the files and I get interesting data from you checker!

I hope you can guide me a little bit on how I can continue with this approach.
Thanks in advance.

**Comment by Attrash-Islam** [comment]
I used `this.errors` here because I couldn't understand how should I communicate between these two functions.

**Comment by Attrash-Islam** [comment]
Give me more time to have a look on how I can implement this.

**Comment by getify** [comment]
Thanks for your willingness to contribute! The idea of integrating with eslint is very much a good idea, but before we can do that we have a lot of work to do changing the interaction with the check() method (what is returned) and especially to work out multi-file checking in Typl. I recommend holding off on this plugin for a bit until that settles down. :)

**Comment by Attrash-Islam** [comment]
![image](https://user-images.githubusercontent.com/7091543/56238338-ebdcfc80-6096-11e9-8ba3-d37e8e43e2a1.png)

😍 I actually added the `loc` in the outputErrorMessages object.

**Comment by Attrash-Islam** [comment]
I'd like to contribute wherever I can to this awesome Repo. Is there any guidelines or some advices on how to do so?

**Comment by getify** [comment]
Can you email me (my same handle on gmail) and we can discuss further?

**Comment by Attrash-Islam** [comment]
Sure. Will send to you 👍

**Comment by Attrash-Islam** [comment]
![image](https://user-images.githubusercontent.com/7091543/56265468-4c4d5780-60f2-11e9-9bd2-58abecf8b694.png)

🌟

**Comment by unlight** [comment]
@Attrash-Islam 
Where `eslint-plugin-typl` is living?

**Comment by Attrash-Islam** [comment]
It's a private repo. Can't publish it yet since it need a lot of work and a changes in the typL core that was tested locally. Also the linter don't support the typL annotation syntax completely. I can share it with you but won't publish it publicly since it's not ready yet
