### ISSUE TITLE
Some words on performance?

### ISSUE THREAD

**Issue by RWOverdijk** [getify/TypL#46]
I saw you request code on Twitter for something called "TypL" so, I googled. Interesting use of tagging! I like the idea of this library a lot. But I wouldn't be me if I didn't get curious. 😄 

Taking a quick look at TypL makes me wonder if performance won't be an issue. Since it's active at runtime as well, doesn't it call a function for every type (because that's what tags are)? If you have a lot of inline typing (loops with large datasets and such) I can imagine this adding some overhead, especially if you're already working with other libraries that have type validation (like MST).

In the same breathe I'd like to mention file size. Can't that be a bit much, too?

Both of these are of course minor concerns, but I couldn't find much about them yet so I figured... Might as well ask.

**Comment by getify** [comment]
The TypL compiler, if you use it, will statically check the type annotations, and any which can be verified statically will be removed, leaving only ones that need to be verified at runtime.

If you don't want the runtime checking, you can have the compiler remove all tag annotations, which of course gives you less reliable checking.

**Comment by RWOverdijk** [comment]
Thanks for your reply :)

How would statically verifying work in runtime?

Also, if people use the tagging wrong, how would that work? They'd just be slapped in the head I guess? 😄

Finally, how do you remove imports for tags? Or would they be globals? Do you use AST for that?

If you mind the questions... Well it's your own fault for building something interesting. I'm not sorry.
